#!/usr/bin/env sh

# --- Play count ---
sticker=$(rmpc sticker get "$FILE" "playCount" | jq -r '.value')
if [ -z "$sticker" ]; then
	rmpc sticker set "$FILE" "playCount" "1"
else
	rmpc sticker set "$FILE" "playCount" "$((sticker + 1))"
fi

# --- Fetch lyrics (only if none exist yet) ---
if [ "$HAS_LRC" = "false" ]; then
	mkdir -p "$(dirname "$LRC_FILE")"

	LYRICS="$(curl -X GET -sG \
		-H "Lrclib-Client: rmpc-$VERSION" \
		--data-urlencode "artist_name=$ARTIST" \
		--data-urlencode "track_name=$TITLE" \
		--data-urlencode "album_name=$ALBUM" \
		"https://lrclib.net/api/get" | jq -r '.syncedLyrics')"

	if [ -z "$LYRICS" ] || [ "$LYRICS" = "null" ]; then
		rmpc remote --pid "$PID" status "No lyrics found for $ARTIST - $TITLE" --level warn
	else
		echo "[ar:$ARTIST]" >"$LRC_FILE"
		echo "[al:$ALBUM]" >>"$LRC_FILE"
		echo "[ti:$TITLE]" >>"$LRC_FILE"
		echo "$LYRICS" | sed -E '/^\[(ar|al|ti):/d' >>"$LRC_FILE"
		rmpc remote --pid "$PID" indexlrc --path "$LRC_FILE"
		rmpc remote --pid "$PID" status "Downloaded lyrics for $ARTIST - $TITLE" --level info
	fi
fi
