music_directory   "~/Music"
user              "juandrzej"
bind_to_address   "127.0.0.1"
port              "6600"
restore_paused    "yes"
auto_update       "yes"
replaygain        "album"
sticker_file      "~/.local/share/mpd/stickers.db"

audio_output {
    type  "pipewire"
    name  "PipeWire"
}

audio_output {
    type   "fifo"
    name   "my_fifo"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}
