music_directory        "~/Music"

user               "juandrzej"
bind_to_address        "127.0.0.1"
port               "6600"
restore_paused "yes"
auto_update    "yes"
replaygain         "album"

audio_output {
    type                "pipewire"
    name                "PipeWire"
}
