"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](magenta)\
$os\
$username\
[](bg:cyan fg:magenta)\
$directory\
[](bg:green2 fg:cyan)\
$git_branch\
$git_status\
[](fg:green2 bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:magenta)\
$conda\
[](fg:magenta bg:blue)\
$time\
[ ](fg:blue)\
$cmd_duration\
$line_break\
$character"""

palette = 'tokyonight_moon'

[os]
disabled = false
style = "bg:magenta fg:black"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:magenta fg:black"
style_root = "bg:magenta fg:black"
format = '[ $user]($style)'

[directory]
style = "bg:cyan fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green2"
format = '[[ $symbol $branch ](fg:black bg:green2)]($style)'

[git_status]
style = "bg:green2"
format = '[[($all_status$ahead_behind )](fg:black bg:green2)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:black bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:black bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:magenta"
format = '[[ $symbol( $context) ](fg:black bg:magenta)]($style)'

[conda]
symbol = "  "
style = "fg:black bg:magenta"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:blue"
format = '[[  $time ](fg:black bg:blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:magenta)'
vimcmd_replace_symbol = '[❮](bold fg:magenta)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:magenta"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.tokyonight_moon]
black = "#1b1d2b"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
green1 = "#4fd6be"
green2 = "#41a6b5"
magenta = "#c099ff"
magenta2 = "#ff007c"
orange = "#ff966c"
purple = "#fca7ea"
red = "#ff757f"
red1 = "#c53b53"
yellow = "#ffc777"
