use_nerdfont = true

statusbar_format = "%artists - %title - %album"

[keybindings]
"Space" = "playpause"

[theme]
background = "#1f2335"
primary = "#c0caf5"
secondary = "#a9b1d6"
title = "#7dcfff"
playing = "#7dcfff"
playing_selected = "#7dcfff"
playing_bg = "#1f2335"
highlight = "#7aa2f7"
highlight_bg = "#24283b"
error = "#f7768e"
error_bg = "#db4b4b"
statusbar = "#24283b"
statusbar_progress = "#9ece6a"
statusbar_bg = "#bb9af7"
cmdline = "#89ddff"
cmdline_bg = "#414868"
