use_nerdfont = true
cover_max_scale = 2
library_tabs = ["albums", "tracks", "playlists", "artists"]
statusbar_format = "%artists - %title - %album"

[keybindings]
"Ctrl+r" = "reload"
"g" = "play"
"Space" = "playpause"
"Shift+q" = "quit"
"q" = "back"
"d" = "move down 7"
"u" = "move up 7"
"Ctrl+s" = "save"
"s" = "noop"
"1" = "focus queue"
"2" = "focus search"
"3" = "focus library"
"4" = "focus cover"

[theme]
background = "default"
# background = "#1f2335"
primary = "#c0caf5"
secondary = "#a9b1d6"
title = "#9ece6a"
playing = "#7dcfff"
highlight = "#7aa2f7"
playing_selected = "#bb9af7"
playing_bg = "#1a1b26"
highlight_bg = "#1a1b26"
error = "#f7768e"
error_bg = "#db4b4b"
# statusbar = "#ff9e64"
statusbar = "#9ece6a"
statusbar_progress = "#9ece6a"
statusbar_bg = "#1a1b26"
cmdline = "#89ddff"
cmdline_bg = "#414868"
search_match = "#f7768e"
