[general]
import = ["~/.config/alacritty/tokyonight_storm.toml",]

[window]
opacity = 0.6

[font]
normal.family = "CodeNewRoman Nerd Font"
 
# [colors]
# transparent_background_colors = true
# draw_bold_text_with_bright_colors = true 
