---
- name: Install packages
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - group_vars/packages.yml

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
